### ISSUE TITLE
I test over PG 9.6 and not show the tree of object (tables,view,function).

### ISSUE THREAD

**Issue by ghost** [gitsql/PostgreSQL-Edition-Windows#1]
I have a Win 64bits and PG 9.6 64bits. With version 9.3 it works well.

**Comment by anupsaund** [comment]
Hi @dbarcena 

We ran some tests and found that the postgresql libraries have changed between 9.5 and 9.6.

Specifically...
The List Databases and List Objects function call to postgresql used to work using the list parameter.
In 9.6 the usage call changed, and the list parameter only works with listing databases, and not in combination with objects.

We raised this as a bug with postgresql.
They have told us that the issue won't be fixed in 9.6 onwards.

gitSQL now have to update the application to work with 9.6.

We will issue an update later this week.

**Comment by jamesjburton** [comment]
Applied fix.

**Comment by jamesjburton** [comment]
Applied fix.

**Comment by mariascott** [comment]
Released in version 1.0.1
